name: "setup-linux"
author: "markvilar"
description: "Sets up system dependencies, and C/C++ compilers for Linux."

runs:
  using: "composite"
  steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Set up GCC
      if: runner.os == 'linux'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Install system dependencies
      if: runner.os == 'linux'
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y \
            cmake \
            gcc-10 \
            clang-12 \
            clang-format \
            ninja-build \
            python3-dev \
            python3-pip \
            pkg-config
        pip3 install --user conan
        export PATH=$PATH:~/.local/bin
